// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlN4lqQwT05a28srhw3fkkqQ-0mU-Tpk',
    appId: '1:87906798445:web:232717a7775d38a0286864',
    messagingSenderId: '87906798445',
    projectId: 'flutterauthen-e2267',
    authDomain: 'flutterauthen-e2267.firebaseapp.com',
    storageBucket: 'flutterauthen-e2267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt1yY7kYmYohHxYWoD7jvnZtCJ4fQyW_I',
    appId: '1:87906798445:android:f9949f48ddffc664286864',
    messagingSenderId: '87906798445',
    projectId: 'flutterauthen-e2267',
    storageBucket: 'flutterauthen-e2267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACyqVG0mWZBf7Bc2xPW7UFqMFJ5dXExI',
    appId: '1:87906798445:ios:c55c89cc5167f6bf286864',
    messagingSenderId: '87906798445',
    projectId: 'flutterauthen-e2267',
    storageBucket: 'flutterauthen-e2267.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACyqVG0mWZBf7Bc2xPW7UFqMFJ5dXExI',
    appId: '1:87906798445:ios:008aabd590903592286864',
    messagingSenderId: '87906798445',
    projectId: 'flutterauthen-e2267',
    storageBucket: 'flutterauthen-e2267.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
